### ISSUE TITLE
事件分析延迟

### ISSUE THREAD

**Issue by yinhediyi** [Qihoo360/WatchAD2.0#10]
说明：两台域控同时向测试环境推日志 一秒大约1000条消息
测试环境配置：16核 32G 
问题描述：

kafka消息积压情况：大约积压2000条左右
硬件使用情况：iatp进程占用20% 内存0.1
事件处理延迟情况： 大约延迟20分钟
线程池使用情况：event_pool、learn_pool 同时running不超过100

尝试增加kafka分区提高消费能力 并未解决问题

**Comment by Cgaii** [comment]
docker容器化部署在一台机器，组件之间相互吃性能，建议将mongo kafka iatp单独部署
