### ISSUE TITLE
server端kafka接收到数据但web端无数据

### ISSUE THREAD

**Issue by Leeasina** [Qihoo360/WatchAD2.0#13]
<img width="1783" alt="image" src="https://github.com/Qihoo360/WatchAD2.0/assets/55623055/e492b8a9-2d90-4c52-97a8-001d123f84cc">
server端已成功部署服务，LDAP登陆WEB也可以进入后台，可以看到系统配置中接入域相关配置、数据源输入配置，但是无法看到实时威胁里的内容
<img width="760" alt="image" src="https://github.com/Qihoo360/WatchAD2.0/assets/55623055/64706fa8-4d08-49c3-83cd-9828d53c7e8e">
<img width="1757" alt="image" src="https://github.com/Qihoo360/WatchAD2.0/assets/55623055/1075aabd-02c4-48e6-83a8-3fc472f2405d">

**Comment by Cgaii** [comment]
> <img alt="image" width="1783" src="https://user-images.githubusercontent.com/55623055/277572377-e492b8a9-2d90-4c52-97a8-001d123f84cc.png"> server端已成功部署服务，LDAP登陆WEB也可以进入后台，可以看到系统配置中接入域相关配置、数据源输入配置，但是无法看到实时威胁里的内容 <img alt="image" width="760" src="https://user-images.githubusercontent.com/55623055/277573522-64706fa8-4d08-49c3-83cd-9828d53c7e8e.png"> <img alt="image" width="1757" src="https://user-images.githubusercontent.com/55623055/277573637-1075aabd-02c4-48e6-83a8-3fc472f2405d.png">

1. 客户端侧可以查看下winlogbeat的日志，确认下生产链路是否有报错：
`C:\ProgramData\winlogbeat\Logs`
2. 服务端侧可以在kafka容器/服务器上找到如下脚本并执行命令，确认消费链路是否正常：
`./bin/kafka-consumer-groups.sh --bootstrap-server 120.0.0.1:9092 --describe --all-groups`
3. 如果链路均正常，可以在agent主机上执行一些攻击测试，比如用户密码重置，再看下告警是否有产生

**Comment by Leeasina** [comment]
kafka数据正常
root@61be54c6b083:/# kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic winlogbeat --from-beginning 正常拿到agent吐的数据
![image](https://github.com/Qihoo360/WatchAD2.0/assets/55623055/eb85a7f7-f5c3-49ac-9ee5-305e3d46cb88)

root@61be54c6b083:/# kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --describe --all-groups

GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                 HOST            CLIENT-ID
iatp            winlogbeat      0          6557            6557            0               sarama-78ae5589-537b-4d00-b278-513c602a200e /192.168.56.108 sarama
这边又用虚拟机搭了一遍，一样的问题，kafka里有事件数据，但是实时威胁里无内容，agent主机上使用mimiktaz等工具不断利用，还是没告警产生

**Comment by Cgaii** [comment]
重置一个用户密码，看下有告警产生吗？

**Comment by Cgaii** [comment]
> kafka数据正常 root@61be54c6b083:/# kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic winlogbeat --from-beginning 正常拿到agent吐的数据 ![image](https://user-images.githubusercontent.com/55623055/277867677-eb85a7f7-f5c3-49ac-9ee5-305e3d46cb88.png)
> 
> root@61be54c6b083:/# kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --describe --all-groups
> 
> GROUP TOPIC PARTITION CURRENT-OFFSET LOG-END-OFFSET LAG CONSUMER-ID HOST CLIENT-ID iatp winlogbeat 0 6557 6557 0 sarama-78ae5589-537b-4d00-b278-513c602a200e /192.168.56.108 sarama 这边又用虚拟机搭了一遍，一样的问题，kafka里有事件数据，但是实时威胁里无内容，agent主机上使用mimiktaz等工具不断利用，还是没告警产生

重置一个用户密码，看下有告警产生吗？

**Comment by Leeasina** [comment]
可以了，辛苦
![image](https://github.com/Qihoo360/WatchAD2.0/assets/55623055/21341d31-eeb0-4b30-8fde-e5024d93016a)

![image](https://github.com/Qihoo360/WatchAD2.0/assets/55623055/a5b44add-88fd-47ca-b9f0-5183757b8b32)
