### ISSUE TITLE
数据源输出配置影响实时威胁正常告警

### ISSUE THREAD

**Issue by Leeasina** [Qihoo360/WatchAD2.0#14]
`{
  "Address": "x.x.x.x:9092",
  "Topic": "ad_out"
}`
这块配置后，不仅topic接受不到数据，实时威胁的告警也不吐了
{
  "Address": "",
  "Topic": ""
}
置空后恢复正常告警

**Comment by Leeasina** [comment]
前端配置出现这样的问题，那后端能够配置数据源输出吗

**Comment by Cgaii** [comment]
后端暂时不支持自定义配置kafka输出。可以先取一下engine.log文件，看有相关报错吗日志吗？
如果是docker部署，可以进入iatp容器中默认目录下查看engine.log

**Comment by Leeasina** [comment]
“发送者创建失败:”，但是容器是可以telnet目标的9092的

**Comment by Leeasina** [comment]
$ ./kafka-console-producer -brokers test.lab:9092 -topic watchad_alert -verbose -value '1'
2023/11/20 15:31:33 Initializing new client
2023/11/20 15:31:33 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2023/11/20 15:31:33 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2023/11/20 15:31:33 client/metadata fetching metadata for all topics from broker test.lab:9092
2023/11/20 15:31:33 Connected to broker at test.lab:9092 (unregistered)
2023/11/20 15:31:33 client/metadata got error from broker -1 while fetching metadata: EOF
2023/11/20 15:31:33 Closed connection to broker test.lab:9092
2023/11/20 15:31:33 client/metadata no available broker to send metadata request to
2023/11/20 15:31:33 client/brokers resurrecting 1 dead seed brokers
2023/11/20 15:31:33 client/metadata retrying after 250ms... (2 attempts remaining)
2023/11/20 15:31:33 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2023/11/20 15:31:33 client/metadata fetching metadata for all topics from broker test.lab:9092
2023/11/20 15:31:33 Connected to broker at test.lab:9092 (unregistered)
2023/11/20 15:31:33 client/metadata got error from broker -1 while fetching metadata: EOF
2023/11/20 15:31:33 Closed connection to broker test.lab:9092
2023/11/20 15:31:33 client/metadata no available broker to send metadata request to
2023/11/20 15:31:33 client/brokers resurrecting 1 dead seed brokers
2023/11/20 15:31:33 client/metadata retrying after 250ms... (1 attempts remaining)
2023/11/20 15:31:33 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2023/11/20 15:31:33 client/metadata fetching metadata for all topics from broker test.lab:9092
2023/11/20 15:31:33 Connected to broker at test.lab:9092 (unregistered)
2023/11/20 15:31:33 client/metadata got error from broker -1 while fetching metadata: EOF
2023/11/20 15:31:33 Closed connection to broker test.lab:9092
2023/11/20 15:31:33 client/metadata no available broker to send metadata request to
2023/11/20 15:31:33 client/brokers resurrecting 1 dead seed brokers
2023/11/20 15:31:34 client/metadata retrying after 250ms... (0 attempts remaining)
2023/11/20 15:31:34 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2023/11/20 15:31:34 client/metadata fetching metadata for all topics from broker test.lab:9092
2023/11/20 15:31:34 Connected to broker at test.lab:9092 (unregistered)
2023/11/20 15:31:34 client/metadata got error from broker -1 while fetching metadata: EOF
2023/11/20 15:31:34 Closed connection to broker test.lab:9092
2023/11/20 15:31:34 client/metadata no available broker to send metadata request to
2023/11/20 15:31:34 client/brokers resurrecting 1 dead seed brokers
2023/11/20 15:31:34 Closing Client
ERROR: Failed to open Kafka producer: kafka: client has run out of available brokers to talk to: EOF

**Comment by Leeasina** [comment]
解决了，kafka端到端版本不对应的问题
